name: Oh_the_dungeons_youll_go
authors: [shadow_wind]
main: otd.Main
load: startup
api-version: 1.14
version: 15.3
softdepend: [WorldEdit,Vault,PlaceholderAPI]
commands:
  oh_the_dungeons:
    aliases: [otd]
    description: Open the OTD world manager
    usage: /<command>
  oh_the_dungeons_place:
    aliases: [otd_place]
    description: Place a dungeon at your current location
    usage: /<command> type
  oh_the_dungeons_cp:
    aliases: [otd_cp]
    description: Copy world config
    usage: /<command> source dest
  oh_the_dungeons_tp:
    aliases: [otd_tp]
    description: open the dungeon plot teleport GUI
    usage: /<command>
  otd_pi:
    description: Open the PerPlayerDungeonInstance Menu
    usage: /<command>
  otd_pi_back:
    description: Back to normal world
    usage: /<command>
  otd_pi_debug:
    description: Show debug info
    usage: /<command>
  otd_pi_create:
    description: Create a dungeon universe with command
    usage: /<command> [player] [generator] [populator] [tower]
permissions:
  oh_the_dungeons.admin:
    default: op
    description: open the inventory GUI
  oh_the_dungeons.teleport:
    default: true
    description: open the dungeon plot teleport GUI
  perplayerdungeoninstance.admin:
    default: op
    description: Using all PerPlayerDungeonInstance management command
  perplayerdungeoninstance.back:
    default: true
    description: Permission for otd_pi_back
  perplayerdungeoninstance.menu:
    default: true
    description: Permission for otd_pi